var assert_counter = require("assert_counter.ltn")
var assert = assert_counter.assert
var assert_not = assert_counter.assert_not
{
    // Void return
    var void_func = \{}
    var teste1 = try(void_func, [])
    assert(teste1:get_error(), "System.Exception: Void ResultUnit created!", "Get error from void result Test 1.")

    var teste2 = try(teste1.unwrap, [teste1])
    assert(teste2:get_error():contains("System.Exception: Operation not supported!"), true, "Unwrap void result Test 1.")
}
return assert_counter.get_error_counter()