var assert_counter = require("assert_counter.ltn")
var assert = assert_counter.assert
var assert_not = assert_counter.assert_not
{
	// Testing try
	var array1
	var a = 1
	var success = try(\(str1, str2){
		write_line(array1[0])
		a = 2
	}, ["oi", "mundo"])
	assert(a, 1, "Failed try() Test 1.")

	success = try(\{
		write_line(array1[0])
		a = 2
	}, null)
	assert(a, 1, "Failed try() Test 2.")

	try(\{
		a = 2
	}, [])
	assert(a, 2, "Failed try() Test 3.")

	var t = Table()
	a = try(\{t.x}, [])
	assert(a, false, "Failed try() Test 4.")

	var broken_func1 = \{eval ("var code =")}
	var broken_result1 = try(broken_func1, [])
	assert(broken_result1, false, "Failed try() Test 5.")


	var broken_func2 = \{eval (#
	write_line(a)
	#)}
	var broken_result2 = try(broken_func2, [])
	assert(broken_result2, false, "Failed try() Test 6.")

	var broken_func3 = \{eval (#
	var a
	a
	(a)
	#)}
	var broken_result3 = try(broken_func3, [])
	assert(broken_result3, true, "Failed try() Test 7.")
}
return assert_counter.get_error_counter()